### ISSUE TITLE
https://github.com/jwlim/tracker_benchmark/blob/master/scripts/butil/seq_config.py#L130 is incorrect

### ISSUE THREAD

**Issue by danielgordon10** [jwlim/tracker_benchmark#10]
This needs a sorted() around it to function properly. Otherwise the file names come in out of order.

**Comment by Peng-YM** [comment]
I meet a problem when I use command `python run_trackers.py`. The error happens when downloading some zip file. Here's the complete stack trace, can you help me solve this? Great thanks.
```
Setup sequences ...
Bird1 does not have img directory
Connecting to http://cvlab.hanyang.ac.kr/tracker_benchmark/seq_new/Bird1.zip ...
Downloading Bird1.zip (9043643 Bytes)..
 557720 (6.17%)
Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 42, in main
    butil.setup_seqs(loadSeqs)
  File "C:\Users\10482\Desktop\tracker_benchmark-master\scripts\butil\seq_config.py", line 53, in setup_seqs
    seqs = make_seq_configs(loadSeqs)
  File "C:\Users\10482\Desktop\tracker_benchmark-master\scripts\butil\seq_config.py", line 123, in make_seq_configs
    download_sequence(name)
  File "C:\Users\10482\Desktop\tracker_benchmark-master\scripts\butil\seq_config.py", line 240, in download_sequence
    download_and_extract_file(url, file_name, SEQ_SRC)
  File "C:\Users\10482\Desktop\tracker_benchmark-master\scripts\butil\seq_config.py", line 274, in download_and_extract_file
    z = zipfile.ZipFile(f)
  File "C:\Program Files\Anaconda2\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Program Files\Anaconda2\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```
