### ISSUE TITLE
TypeError('unsupported data type unicode',)

### ISSUE THREAD

**Issue by xingkongliang** [jwlim/tracker_benchmark#3]
When I ran this demo, I ran 'python run_tracker.py' and then there some wrong, could you give me some suggestion?
`
failed to execute LOT : (<type 'exceptions.TypeError'>, TypeError('unsupported data type unicode',), <traceback object at 0x7fd4c7c87f38>)
Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/hanzhj/ZTL_projects/Tracking/tracker_benchmark/scripts/butil/load_results.py", line 5, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range
`

**Comment by ihpdep** [comment]
Same problem on CentOS Linux release 7.1.1503 (Core), Python 2.7.12 :: Continuum Analytics, Inc. and Matlab 2014b

Input Test name : test
Starting benchmark for 24 trackers, evalTypes : ['OPE', 'SRE', 'TRE']
1_ASLA, 1_Basketball:1/1 - OPE
Starting matlab engine...
failed to execute ASLA : (<type 'exceptions.TypeError'>, TypeError('unsupported data type unicode',), <traceback object at 0x7f225535a320>)
Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "/home/ihpdep/codes/tracker_benchmark/scripts/butil/load_results.py", line 5, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

**Comment by ihpdep** [comment]
It seems that Matlab 2014b has some issues with python integration.  It works on Win10, Matlab 2016a.

**Comment by ihpdep** [comment]
Works on Matlab 2015b and Matlab 2016a.

**Comment by dhruvmullick** [comment]
Facing the same issue. Matlab 2014b. Probably the matlab engines of pre 2015b aren't able to run the code. 
@jwlim , can you suggest please a fix for this problem?
