### ISSUE TITLE
failed to execute ASLA

### ISSUE THREAD

**Issue by MBehtemam** [jwlim/tracker_benchmark#6]
i copy the images "car4" to "data/car4" directory and then change tb_50.txt files to this : 

    Car4	IV ,SV

then try to run this code but i get these errors : 
    
    PS C:\Users\Mohammad\Desktop\tracker_benchmark-master> python run_trackers.py -s tb50
Setup sequences ...
        Car4    ./data/Car4/img/
Input Test name : Mohammad
Starting benchmark for 24 trackers, evalTypes : ['OPE', 'SRE', 'TRE']
1_ASLA, 1_Car4:1/1 - OPE
Starting matlab engine...
Undefined function or variable 'vl_setup'.

Error in run_ASLA (line 5)
vl_setup;

failed to execute ASLA : (<class 'matlab.engine.MatlabExecutionError'>, MatlabExecutionError("\n  File C:\\Users\\Mohammad\\Desktop\\tracker_benchmark-
master\\trackers\\ASLA\\run_ASLA.m, line 5, in run_ASLA\nUndefined function or variable 'vl_setup'.\n",), <traceback object at 0x00000000036E6548>)
Traceback (most recent call last):
  File "run_trackers.py", line 146, in <module>
    main(sys.argv[1:])
  File "run_trackers.py", line 50, in main
    trackers, seqs, evalType, shiftTypeSet)
  File "run_trackers.py", line 138, in run_trackers
    butil.save_seq_result(seqResults)
  File "C:\Users\Mohammad\Desktop\tracker_benchmark-master\scripts\butil\load_results.py", line 5, in save_seq_result
    tracker = result[0].tracker
IndexError: list index out of range

**Comment by SMZCC** [comment]
#### Hello, I have encountered the same problem.  Have you solved the problem? @MBehtemam And how?

**Comment by aaon22357** [comment]
@SMZCC   hello, have you solved this? I met the same problem~

**Comment by SMZCC** [comment]
No, I just given up :cry: @aaon22357

**Comment by aaon22357** [comment]
@SMZCC  Thank you as well ~

**Comment by UndecidedBoy** [comment]
Hello,
I had the same problem as stated above with ASLA.
I managed to solve this error by:
- Downloading VLFeat from http://www.vlfeat.org/download.html
- Adding the path from the VLFeat library jsut downloaded in the MatLab paths.
    -> Open MatLab
    -> addpath('Path\to\VLFeat\Location')
    -> savepath

It just takes tremendous time to output something from the cmd window...
Hope this helps :)
Nice day all !
